algoritmo "ex2Start"
var
   palavra1, palavra2, palavra3: caractere
   num1, num2, num3: inteiro
inicio
      escreva("Palavra 1: ")
      leia(palavra1)
      escreva("Palavra 2: ")
      leia(palavra2)
      escreva("Número 1: ")
      leia(num1)
      escreva("Número 2: ")
      leia(num2)

      palavra3 <- palavra1 + palavra2
      num3 <- num1 + num2
      
      escreval(palavra3)
      escreval(num3)
fimalgoritmo