algoritmo "ex4start"
var
   num1, num2, soma, mult, sub, divisao: real
inicio
      escreva("N1: ")
      leia(num1)
      escreva("N2: ")
      leia(num2)
      soma <- num1 + num2
      sub <- num1 - num2
      mult <- num1 * num2
      divisao <- num1 / num2
      escreval("Soma: ", soma)
      escreval("Subtração: ", sub)
      escreval("Multiplicação: ", mult)
      escreval("Divisão: ", divisao)

fimalgoritmo